info:
  projects:
    test: credem-aiddai-workarea-test
  service_account: aiddai-tech-sa
  kms_keys:
    test: projects/credem-googcp-keys-test/locations/europe-west8/keyRings/hsm-keys-test-west8/cryptoKeys/cypherkey-hsm-test-west8

cloud_function:
  test:
    bucket:
      name: test-cf-bucket-ainex3
      location: europe-west8
      create_new: true
    functions:
      hello-world:
        name: hello-world
        description: "hello world function"
        version: 2
        region: europe-west8
        source_folder: .
        trigger_config:
          trigger: http
          allow_unauthenticated: false
        env_variables: {}
        ingress_settings: "ALLOW_ALL"