info:
  projects:
    dev: your-dev-project-id
    prd: your-prd-project-id
  service_account: your-service-account-name

cloud_function:
  dev:
    bucket:
      name: my-bundle-bucket
      location: europe-west1
      create_new: true
    functions:
      hello-world:
        name: hello-world
        description: "Simple hello world function"
        region: europe-west1
        source_folder: .
        trigger_config:
          trigger: http
          allow_unauthenticated: true
        env_variables: {}
        ingress_settings: "ALLOW_ALL"
